### ISSUE TITLE
Error on startup of sample portlet

### ISSUE THREAD

**Issue by tvhdev** [amusarra/liferay-7-jsf-primefaces-portlet#1]
Hello, im on liferay 7.4.3.4-ga4 and im getting this error on startup:

2021-12-21 21:26:47.102 ERROR [fileinstall-directory-watcher][DirectoryWatcher:1160] Unable to start bundle: webbundle:/opt/liferay/osgi/war/liferay-7-jsf-primefaces-portlet.war?Bundle-SymbolicName=liferay-7-jsf-primefaces-portlet&Web-ContextPath=/liferay-7-jsf-primefaces-portlet&protocol=file
com.liferay.portal.kernel.log.LogSanitizerException: org.osgi.framework.BundleException: Could not resolve module: liferay-7-jsf-primefaces-portlet [1433]_  Unresolved requirement: Import-Package: com.google.zxing.qrcode.decoder; resolution:="optional"_  Unresolved requirement: Import-Package: com.hazelcast.config; resolution:="optional"_  Unresolved requirement: Import-Package: com.hazelcast.core; resolution:="optional"_  Unresolved requirement: Import-Package: com.ibm.uvm.tools; resolution:="optional"_  Unresolved requirement: Import-Package: com.lowagie.text; resolution:="optional"_  Unresolved requirement: Import-Package: com.lowagie.text.pdf; resolution:="optional"_  Unresolved requirement: Import-Package: com.rometools.rome.feed.synd; resolution:="optional"_  Unresolved requirement: Import-Package: com.rometools.rome.io; resolution:="optional"_  Unresolved requirement: Import-Package: com.sun.enterprise; resolution:="optional"_  Unresolved requirement: Import-Package: com.sun.enterprise.deployment; resolution:="optional"_  Unresolved requirement: Import-Package: com.sun.jdmk.comm; resolution:="optional"_  Unresolved requirement: Import-Package: groovy.lang; resolution:="optional"_  Unresolved requirement: Import-Package: groovy.util; resolution:="optional"_  Unresolved requirement: Import-Package: it.dontesta.labs.services.temperature.model; resolution:="optional"_  Unresolved requirement: Import-Package: it.dontesta.labs.services.temperature.service; resolution:="optional"_  Unresolved requirement: Import-Package: javax.ejb; resolution:="optional"_  Unresolved requirement: Import-Package: javax.faces.component.search; resolution:="optional"_  Unresolved requirement: Import-Package: javax.jmdns; resolution:="optional"_  Unresolved requirement: Import-Package: javax.jms; resolution:="optional"_  Unresolved requirement: Import-Package: net.fortuna.ical4j.model; resolution:="optional"_  Unresolved requirement: Import-Package: net.fortuna.ical4j.model.property; resolution:="optional"_  Unresolved requirement: Import-Package: net.glxn.qrgen; resolution:="optional"_  Unresolved requirement: Import-Package: net.glxn.qrgen.image; resolution:="optional"_  Unresolved requirement: Import-Package: net.sf.ehcache; resolution:="optional"_  Unresolved requirement: Import-Package: org.apache; resolution:="optional"_  Unresolved requirement: Import-Package: org.apache.axis.tools.ant.wsdl; resolution:="optional"_  Unresolved requirement: Import-Package: org.apache.jasper.compiler; resolution:="optional"_  Unresolved requirement: Import-Package: org.apache.poi.hssf.usermodel; resolution:="optional"_  Unresolved requirement: Import-Package: org.apache.poi.hssf.util; resolution:="optional"_  Unresolved requirement: Import-Package: org.apache.poi.ss.usermodel; resolution:="optional"_  Unresolved requirement: Import-Package: org.apache.poi.ss.util; resolution:="optional"_  Unresolved requirement: Import-Package: org.apache.poi.xssf.streaming; resolution:="optional"_  Unresolved requirement: Import-Package: org.apache.poi.xssf.usermodel; resolution:="optional"_  Unresolved requirement: Import-Package: org.apache.xmlbeans.impl.common; resolution:="optional"_  Unresolved requirement: Import-Package: org.ehcache; resolution:="optional"_  Unresolved requirement: Import-Package: org.ehcache.config; resolution:="optional"_  Unresolved requirement: Import-Package: org.ehcache.config.builders; resolution:="optional"_  Unresolved requirement: Import-Package: org.ehcache.xml; resolution:="optional"_  Unresolved requirement: Import-Package: org.icefaces.ace.component.fileentry; resolution:="optional"_  Unresolved requirement: Import-Package: org.krysalis.barcode4j; resolution:="optional"_  Unresolved requirement: Import-Package: org.krysalis.barcode4j.impl; resolution:="optional"_  Unresolved requirement: Import-Package: org.krysalis.barcode4j.impl.codabar; resolution:="optional"_  Unresolved requirement: Import-Package: org.krysalis.barcode4j.impl.code128; resolution:="optional"_  Unresolved requirement: Import-Package: org.krysalis.barcode4j.impl.code39; resolution:="optional"_  Unresolved requirement: Import-Package: org.krysalis.barcode4j.impl.datamatrix; resolution:="optional"_  Unresolved requirement: Import-Package: org.krysalis.barcode4j.impl.int2of5; resolution:="optional"_  Unresolved requirement: Import-Package: org.krysalis.barcode4j.impl.pdf417; resolution:="optional"_  Unresolved requirement: Import-Package: org.krysalis.barcode4j.impl.postnet; resolution:="optional"_  Unresolved requirement: Import-Package: org.krysalis.barcode4j.impl.upcean; resolution:="optional"_  Unresolved requirement: Import-Package: org.krysalis.barcode4j.output; resolution:="optional"_  Unresolved requirement: Import-Package: org.krysalis.barcode4j.output.bitmap; resolution:="optional"_  Unresolved requirement: Import-Package: org.krysalis.barcode4j.output.svg; resolution:="optional"_  Unresolved requirement: Import-Package: org.mortbay.jetty.annotations; resolution:="optional"_  Unresolved requirement: Import-Package: org.mortbay.jetty.handler; resolution:="optional"_  Unresolved requirement: Import-Package: org.mortbay.jetty.plus.annotation; resolution:="optional"_  Unresolved requirement: Import-Package: org.mortbay.jetty.webapp; resolution:="optional"_  Unresolved requirement: Import-Package: org.owasp.html; resolution:="optional"_  Unresolved requirement: Import-Package: com.liferay.portal.service; resolution:="optional"_  Unresolved requirement: Import-Package: com.liferay.portal.osgi.web.servlet.jsp.compiler; resolution:="optional"_  Unresolved requirement: Import-Package: com.liferay.portal.spring.context; resolution:="optional"_  Unresolved requirement: Require-Capability: osgi.ee; filter:="(&(osgi.ee=JavaSE)(version=11))"_ [Sanitized]

**Comment by amusarra** [comment]
Hi @tvhdev this version of the project is tested on the Liferay 7.3.5-ga6. This project will be reviewed for the release 7.4 but I don't know when I will do it.

**Comment by amusarra** [comment]
Hi @tvhdev 
Can you can try again?

**Comment by tvhdev** [comment]
Hello, yes, will do. Btw, did you change the instructions ? The submodule with the service builder project seems to be missing?

Execution failed for task ':compileJava'.
> Could not resolve all files for configuration ':compileClasspath'.
   > Could not resolve it.dontesta.labs.services.temperature:it.dontesta.labs.services.temperature.api:2.0.0.
     Required by:
         project :
      > Could not resolve it.dontesta.labs.services.temperature:it.dontesta.labs.services.temperature.api:2.0.0.
         > Could not get resource 'https://maven.pkg.github.com/amusarra/sample-temperature-service-builder/it/dontesta/labs/services/temperature/it.dontesta.labs.services.temperature.api/2.0.0/it.dontesta.labs.services.temperature.api-2.0.0.pom'.
            > Could not GET 'https://maven.pkg.github.com/amusarra/sample-temperature-service-builder/it/dontesta/labs/services/temperature/it.dontesta.labs.services.temperature.api/2.0.0/it.dontesta.labs.services.temperature.api-2.0.0.pom'. Received status code 401 from server: Unauthorized

**Comment by tvhdev** [comment]
Sorry, i used version 2.0.0, i will try again with version 1.0.0

**Comment by tvhdev** [comment]
2021-12-22 22:14:40.573 INFO  [fileinstall-directory-watcher][BaseDeployer:871] Deploying liferay-7-jsf-primefaces-portlet.war
  Warning: META-INF\MANIFEST.MF modified in the future.
  Warning: WEB-INF\classes\i18n.properties modified in the future.
  Warning: WEB-INF\classes\it\dontesta\labs\liferay\portlet\jsf\DataGridView.class modified in the future.
  Warning: WEB-INF\classes\it\dontesta\labs\liferay\portlet\jsf\ExampleAccessToOSGiService.class modified in the future.
  Warning: WEB-INF\classes\it\dontesta\labs\liferay\portlet\jsf\TemperatureLocalServiceTracker.class modified in the future.
  Warning: WEB-INF\classes\it\dontesta\labs\liferay\portlet\jsf\UserLocalServiceTracker.class modified in the future.
  Warning: WEB-INF\classes\log4j.properties modified in the future.
  Warning: WEB-INF\liferay-plugin-package.properties modified in the future.
  Warning: WEB-INF\resources\css\main.css modified in the future.
  Warning: WEB-INF\resources\images\devices\icons8-iot-sensor-0-50.png modified in the future.
  Warning: WEB-INF\resources\images\devices\icons8-iot-sensor-1-50.png modified in the future.
  Warning: WEB-INF\resources\images\devices\icons8-iot-sensor-filled-50.png modified in the future.
  Warning: WEB-INF\views\view.xhtml modified in the future.
  Warning: resources\images\icon.png modified in the future.
2021-12-22 22:14:40.978 INFO  [fileinstall-directory-watcher][BaseAutoDeployListener:50] Portlets for E:\data\liferay-blade-samples\liferay-workspace\bundles\tomcat-9.0.37\temp\20211222221440450IDKZNHMH\liferay-7-jsf-primefaces-portlet.war copied successfully
2021-12-22 22:14:42.916 ERROR [fileinstall-directory-watcher][WabBundleProcessor:244] Catastrophic initialization failure! Shutting down liferay-7-jsf-primefaces-portlet WAB due to: java.lang.NoClassDefFoundError: Lit/dontesta/labs/services/temperature/model/Temperature;
java.lang.RuntimeException: java.lang.NoClassDefFoundError: Lit/dontesta/labs/services/temperature/model/Temperature;
	at com.sun.faces.config.ConfigureListener.contextInitialized(ConfigureListener.java:292)
	at com.liferay.portal.osgi.web.wab.extender.internal.adapter.ServletContextListenerExceptionAdapter._initializeContext(ServletContextListenerExceptionAdapter.java:119)
	at com.liferay.portal.osgi.web.wab.extender.internal.adapter.ServletContextListenerExceptionAdapter.contextInitialized(ServletContextListenerExceptionAdapter.java:99)
	at jdk.internal.reflect.GeneratedMethodAccessor183.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.http.servlet.internal.registration.ListenerRegistration$EventListenerInvocationHandler.invoke(ListenerRegistration.java:143)
	at com.sun.proxy.$Proxy793.contextInitialized(Unknown Source)
	at org.eclipse.equinox.http.servlet.internal.context.ContextController.doAddListenerRegistration(ContextController.java:350)
	at org.eclipse.equinox.http.servlet.internal.context.ContextController.addListenerRegistration(ContextController.java:303)
	at org.eclipse.equinox.http.servlet.internal.customizer.ContextListenerTrackerCustomizer.addingService(ContextListenerTrackerCustomizer.java:71)
	at org.eclipse.equinox.http.servlet.internal.customizer.ContextListenerTrackerCustomizer.addingService(ContextListenerTrackerCustomizer.java:1)
	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:943)
	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:1)
	at org.osgi.util.tracker.AbstractTracked.trackAdding(AbstractTracked.java:256)
	at org.osgi.util.tracker.AbstractTracked.track(AbstractTracked.java:229)
	at org.osgi.util.tracker.ServiceTracker$Tracked.serviceChanged(ServiceTracker.java:903)
	at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:109)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:891)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:804)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:127)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:228)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:469)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:487)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:1004)
	at com.liferay.portal.osgi.web.wab.extender.internal.WabBundleProcessor.initListeners(WabBundleProcessor.java:625)
	at com.liferay.portal.osgi.web.wab.extender.internal.WabBundleProcessor.init(WabBundleProcessor.java:231)
	at com.liferay.portal.osgi.web.wab.extender.internal.WebBundleDeployer._initWabBundle(WebBundleDeployer.java:159)
	at com.liferay.portal.osgi.web.wab.extender.internal.WebBundleDeployer.doStart(WebBundleDeployer.java:88)
	at com.liferay.portal.osgi.web.wab.extender.internal.WabFactory$WABExtension.start(WabFactory.java:115)
	at com.liferay.portal.osgi.web.wab.extender.internal.WabFactory.addingBundle(WabFactory.java:68)
	at com.liferay.portal.osgi.web.wab.extender.internal.WabFactory.addingBundle(WabFactory.java:50)
	at org.osgi.util.tracker.BundleTracker$Tracked.customizerAdding(BundleTracker.java:475)
	at org.osgi.util.tracker.BundleTracker$Tracked.customizerAdding(BundleTracker.java:1)
	at org.osgi.util.tracker.AbstractTracked.trackAdding(AbstractTracked.java:256)
	at org.osgi.util.tracker.AbstractTracked.track(AbstractTracked.java:229)
	at org.osgi.util.tracker.BundleTracker$Tracked.bundleChanged(BundleTracker.java:450)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:908)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:148)
	at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEventPrivileged(EquinoxEventPublisher.java:230)
	at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEvent(EquinoxEventPublisher.java:137)
	at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEvent(EquinoxEventPublisher.java:129)
	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor.publishModuleEvent(EquinoxContainerAdaptor.java:191)
	at org.eclipse.osgi.container.Module.publishEvent(Module.java:476)
	at org.eclipse.osgi.container.Module.doStart(Module.java:578)
	at org.eclipse.osgi.container.Module.start(Module.java:449)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:428)
	at com.liferay.portal.file.install.internal.DirectoryWatcher._startBundle(DirectoryWatcher.java:1097)
	at com.liferay.portal.file.install.internal.DirectoryWatcher._startBundles(DirectoryWatcher.java:1130)
	at com.liferay.portal.file.install.internal.DirectoryWatcher._process(DirectoryWatcher.java:992)
	at com.liferay.portal.file.install.internal.DirectoryWatcher.run(DirectoryWatcher.java:282)
Caused by: java.lang.NoClassDefFoundError: Lit/dontesta/labs/services/temperature/model/Temperature;
	at java.base/java.lang.Class.getDeclaredFields0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredFields(Class.java:3061)
	at java.base/java.lang.Class.getDeclaredFields(Class.java:2248)
	at com.sun.faces.application.annotation.ManagedBeanConfigHandler.collectAnnotatedFields(ManagedBeanConfigHandler.java:242)
	at com.sun.faces.application.annotation.ManagedBeanConfigHandler.getBeanInfo(ManagedBeanConfigHandler.java:151)
	at com.sun.faces.application.annotation.ManagedBeanConfigHandler.process(ManagedBeanConfigHandler.java:137)
	at com.sun.faces.application.annotation.ManagedBeanConfigHandler.push(ManagedBeanConfigHandler.java:123)
	at com.sun.faces.application.annotation.AnnotationManager.applyConfigAnnotations(AnnotationManager.java:234)
	at com.sun.faces.config.processor.AbstractConfigProcessor.processAnnotations(AbstractConfigProcessor.java:446)
	at com.sun.faces.config.processor.ManagedBeanConfigProcessor.process(ManagedBeanConfigProcessor.java:244)
	at com.sun.faces.config.processor.AbstractConfigProcessor.invokeNext(AbstractConfigProcessor.java:152)
	at com.sun.faces.config.processor.ValidatorConfigProcessor.process(ValidatorConfigProcessor.java:120)
	at com.sun.faces.config.processor.AbstractConfigProcessor.invokeNext(AbstractConfigProcessor.java:152)
	at com.sun.faces.config.processor.ConverterConfigProcessor.process(ConverterConfigProcessor.java:126)
	at com.sun.faces.config.processor.AbstractConfigProcessor.invokeNext(AbstractConfigProcessor.java:152)
	at com.sun.faces.config.processor.ComponentConfigProcessor.process(ComponentConfigProcessor.java:117)
	at com.sun.faces.config.processor.AbstractConfigProcessor.invokeNext(AbstractConfigProcessor.java:152)
	at com.sun.faces.config.processor.ApplicationConfigProcessor.process(ApplicationConfigProcessor.java:362)
	at com.sun.faces.config.processor.AbstractConfigProcessor.invokeNext(AbstractConfigProcessor.java:152)
	at com.sun.faces.config.processor.LifecycleConfigProcessor.process(LifecycleConfigProcessor.java:137)
	at com.sun.faces.config.processor.AbstractConfigProcessor.invokeNext(AbstractConfigProcessor.java:152)
	at com.sun.faces.config.processor.FactoryConfigProcessor.process(FactoryConfigProcessor.java:239)
	at com.sun.faces.config.ConfigManager.initialize(ConfigManager.java:439)
	at com.sun.faces.config.ConfigureListener.contextInitialized(ConfigureListener.java:227)
	... 51 more
Caused by: java.lang.ClassNotFoundException: it.dontesta.labs.services.temperature.model.Temperature cannot be found by liferay-7-jsf-primefaces-portlet_1.0.0
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:508)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:419)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:411)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:151)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 75 more
2021-12-22 22:14:42.935 INFO  [fileinstall-directory-watcher][BundleStartStopLogger:46] STARTED liferay-7-jsf-primefaces-portlet_1.0.0 [1432

**Comment by amusarra** [comment]
Hi @tvhdev 
Updated the section Quick Start on the README file. The build procedure is:

```bash
# Steo 1 - Clone, build and install the Sample Temperature Service
$ cd ~
$ git clone https://github.com/amusarra/sample-temperature-service-builder.git
$ cd sample-temperature-service-builder
$ ./gradlew clean install

# Step 2 -  Clone and build JSF PrimeFaces Portlet
$ cd ~
$ git clone https://github.com/amusarra/liferay-7-jsf-primefaces-portlet.git
$ cd liferay-7-jsf-primefaces-portlet
$ ./gradlew clean build
```

In this way it should work fine.
